#!/usr/bin/env bash

set -eu

cwd="$(cd "$(dirname "$0")" && pwd)"
# shellcheck disable=SC1090
source "$cwd/common"

dir=$(mktemp -d -t test-check.XXXXXX)

it "produces the time as a version, so webhook is always triggered"

time_before="$(date +%s)"
check_result="$(run check '{source: {token: "123"}}' "$dir")"

time="$(jq --exit-status --raw-output ".[0].time" <<< "$check_result" )"

assert_gte "$time" "$time_before"