#!/usr/bin/env bash

set -eu

cwd="$(cd "$(dirname "$0")" && pwd)"
# shellcheck disable=SC1090
source "$cwd/common"

dir=$(mktemp -d -t test-check.XXXXXX)

it "produces a version on first run"
assert_equal_json \
    '[ {
         action: "export",
         bitIds: [
           "boclips._ui/badge@1.0.4"
         ],
         username: "remo1"
       } ]' \
    "$(run check '{
        source: {
            action: "export",
             bitIds: [
               "boclips._ui/badge@1.0.4"
             ],
             username: "remo1"
        }
    }' \
    "$dir" \
    2> "$dir/stderr")"
