#!/usr/bin/env bash

set -eu

it () {
    echo "$@"
}

resource_output_dir () {
    local dir=/tmp/bit-resource
    mkdir --parents "$dir"
    echo "$dir"
}

run () {
    cmd="$cwd/../resource/$1"
    input="$(json "$2")"
    dir=$3
    (
    cd "$dir"
    $cmd "$(resource_output_dir)" <<< "$input"
    )
}

json () {
    jq --null-input "$@"
}

assert_equal_json () {
    lhs="$(json "$1")"
    rhs="$(json "$2")"
    assert_equal "$lhs" "$rhs"
}

green () {
    echo "$(tput setaf 2)$*$(tput sgr0)"
}

red () {
    echo "$(tput setaf 1)$*$(tput sgr0)"
}

assert_equal () {
    if [ "$1" == "$2" ]
    then
        green "Test passed"
        echo
    else
        fail "$1" "==" "$2"
    fi
}

assert_gte () {
    if (( "$1" >= "$2" ))
    then
        green "Test passed"
        echo
    else
        fail "$1" ">=" "$2"
    fi
}

fail () {
    red "Test failed"
        echo
        echo "Expected output:"
        echo "$1"
        echo
        echo "to be $2:"
        echo "$3"
        echo
        exit 1
}