#!/usr/bin/env bash

set -e

cwd="$(cd "$(dirname "$0")" && pwd)"
# shellcheck disable=SC1090
source "$cwd/common"

dir=$(mktemp -d -t test-in.XXXXXX)

input="$(json '
{
    source: {},
    version: {
        time: "1590070626"
    },
    params: {}
}
')"

output="$(run in \
    "$input" \
    "$dir"
    )"

it "emits the received version"

assert_equal_json \
    '{
  version: {
        time: "1590070626"
  },
  metadata: [
    { name: "time", value: "1590070626" }
  ]
}' \
    "$output"